QCBM algorithm
mit-han-lab/torchquantum pull request #271
Opened 2024-05-31 18:55 UTC by Gopal-Dahale

## Purpose
Added Quantum Circuit Born Machine (QCBM) algorithm.

## Details
- QCBM and MMDLoss classes are added in `torchquantum/algorithms`.
- Added an example demonstrating generative modelling with QCBM on Gaussian Mixture.
- Resolves #264.

## Mentions
@GenericP3rson

2024-06-02 18:22 UTC, Gopal-Dahale commented
@GenericP3rson Can you help me with this `flake8` error in github actions.

2024-06-02 21:20 UTC, GenericP3rson commented
Hi, don’t worry about getting that working, you just need to pass the functional tests!

2024-06-02 21:33 UTC, GenericP3rson requested changes
Great work so far! Main thing to change is formatting, see comments below. Thanks for the great work and feel free to reach out with questions!

2024-06-02 21:33 UTC, GenericP3rson commented on examples/QCBM/README.md
> +
You should definitely add attribution (Implementation By: [Your Name])!

2024-06-02 21:33 UTC, GenericP3rson commented on examples/QCBM/qcbm_gaussian_mixture.py
Two format suggestions:
(1) Can you pass command line parameters to this example? (Specifically, use `argparse` to add parameters on whether or not to plot, n_wires, epochs, and essentially all of the mixture parameters — you can find an example in `examples/mnist/mnist.py`.) You’ll also need to add a simple description on how to use it in the README. The idea of this is we want to be able to run some MVP example in our CI to make sure the example stays up to date

(2) Also, if you could make this example into a simple notebook (no need to add parameters for the notebook itself), that would be great! Adding a bit of text to explain what’s going on in the notebook would be useful as well!

2024-06-03 07:59 UTC, Gopal-Dahale commented on examples/QCBM/qcbm_gaussian_mixture.py
@GenericP3rson 
1. Added command line arguments to the Python file and updated the readme.
2. I think adding a jupyter notebook will result in code duplication. If it works, I can add some text in the Python file. I have added a visualization of the result (plot of learnt Gaussian mixture) in the README.md. Let me know your on this part.

2024-06-05 16:25 UTC, GenericP3rson commented on examples/QCBM/qcbm_gaussian_mixture.py
(By the way, thanks for your patience! You raise a really excellent point on code duplication; I’m going to touch base with the rest of the team to decide a standard for our examples tonight then will get back to you!)

2024-06-06 02:43 UTC, GenericP3rson commented on examples/QCBM/qcbm_gaussian_mixture.py
Hello, I discussed with the team! We think having a notebook to introduce the background and functionality would be very helpful to users. To help reduce code replication, you can try importing some of the functions from the Python file. And if you must replicate code, that’s also totally fine by us!

By the way, really, really great work so far!

2024-06-06 08:58 UTC, Gopal-Dahale commented on examples/QCBM/qcbm_gaussian_mixture.py
@GenericP3rson I have added a jupyter notebook which introduces QCBM.

2024-06-06 15:50 UTC, GenericP3rson requested changes
Great work! A few last minor changes. If you could just keep the tabbing consistent in the qcbm.py file, that would be great! (A few examples are suggested—note that there might be some oddities with the spaces converting properly into tabs. I think it would be most optimal to just double-check that everything is consistent in the file itself.)

2024-06-06 15:50 UTC, GenericP3rson commented on torchquantum/algorithm/qcbm.py
> +			px: First probability distribution
```suggestion
		px: First probability distribution
```

2024-06-06 15:50 UTC, GenericP3rson commented on torchquantum/algorithm/qcbm.py
> +			py: Second probability distribution
```suggestion
		py: Second probability distribution
```

2024-06-06 15:50 UTC, GenericP3rson commented on torchquantum/algorithm/qcbm.py
> +
```suggestion
    Args:
```

2024-06-06 15:50 UTC, GenericP3rson commented on torchquantum/algorithm/qcbm.py
> +        px: First probability distribution
```suggestion
            px: First probability distribution
```

2024-06-06 15:50 UTC, GenericP3rson commented on torchquantum/algorithm/qcbm.py
> +        py: Second probability distribution
```suggestion
            py: Second probability distribution
```

2024-06-06 16:12 UTC, Gopal-Dahale commented
@GenericP3rson what do you think about formatting now?

2024-06-11 16:59 UTC, GenericP3rson approved these changes
Good to go!

2024-06-12 14:06 UTC, Hanrui-Wang approved these changes

2024-06-12 14:07 UTC, merged