Fix for issue #213
mit-han-lab/torchquantum pull request #289
Opened 2024-11-18 19:09 UTC by ankhoa1212

To fix the error in issue #213, it looks like the ```QuantumDevice``` needs to be initialized with the batch size (batch size is 1 by default which is why the size was [1, 2] instead of [256, 2]). 

After this change, there is a ```NameError``` for ```CliffordQuantizer```:
![image](https://github.com/user-attachments/assets/c79abc0e-3d3f-457c-bfd8-77d6c9ec306b)
which can be fixed by importing it in the ```torchquantum/operator/op_types.py``` file, which calls the ```CliffordQuantizer``` function.

After these changes, I believe ```examples/clifford_qnn/mnist_clifford_qnn.py``` can run out-of-the-box:
![clifford_success](https://github.com/user-attachments/assets/18255da5-d26c-40f0-a72a-c817b70ce261)

2024-11-18 20:53 UTC, 01110011011101010110010001101111 requested changes
Thanks for figuring this out! Just a quick question on the extra import then I can merge this in!

2024-11-18 21:09 UTC, 01110011011101010110010001101111 requested changes

2024-11-18 21:09 UTC, 01110011011101010110010001101111 commented on torchquantum/operator/op_types.py
> +from torchquantum.util.quantization.clifford_quantization import CliffordQuantizer
Oh, wait, I missed your initial comment.

2024-11-18 21:09 UTC, 01110011011101010110010001101111 commented on torchquantum/operator/op_types.py
> +from torchquantum.util.quantization.clifford_quantization import CliffordQuantizer
Can you instead import this lazily, so in the conditional branch where we actually call `CliffordQuantizer`? Afterward, will merge in!

2024-11-18 21:10 UTC, 01110011011101010110010001101111 commented
Also, don’t worry about tests, it’s likely from numpy 2.0 breaking. Once we merge, I think we should be good.

2024-11-19 03:14 UTC, ankhoa1212 commented
Alright I moved the import into the conditional branch, so it should be good now.

2024-11-19 09:28 UTC, merged

2024-11-19 09:28 UTC, 01110011011101010110010001101111 commented
Merged, thanks so much!